version: "3.5"
services:

  pgmaster:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=sbp
      - POSTGRES_PASSWORD=sbp
      - PG_REP_USER=replica
      - POSTGRES_DB=app
    networks:
      bpnet:
        aliases:
          - psql

  rabbit:
    image: "rabbitmq:3.7.18-management-alpine"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "rabbitmq"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: "rabbitmq"


  app:
    build: . # todo: add specific dockerfile and args
    restart: on-failure
    depends_on:
      - pgmaster
    networks:
      - bpnet

  app_db_init:
    build:
      context: .
      dockerfile: Dockerfile.dbinit
      args:
        CONFIG_FOLDER: "./storage/config_templates/docker"
    networks:
      - bpnet

  web_app:
    build:
      context: .
      dockerfile: Dockerfile.web
networks:
  bpnet:
    driver: bridge
    name: bpnet

volumes:
  bpdata:


