"""empty message

Revision ID: 13885ad9dbd6
Revises: 32ae247f13ad
Create Date: 2021-11-16 18:35:59.240316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13885ad9dbd6'
down_revision = '32ae247f13ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('towers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('healt', sa.BigInteger(), nullable=False),
    sa.Column('defense', sa.BigInteger(), nullable=False),
    sa.Column('defender_count', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defenders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('attack_points_generated', sa.BigInteger(), nullable=False),
    sa.Column('defense_points_generated', sa.BigInteger(), nullable=False),
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('global_defender_count', sa.BigInteger(), nullable=False),
    sa.Column('hocus_tower_id', sa.Integer(), nullable=True),
    sa.Column('pocus_tower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hocus_tower_id'], ['towers.id'], ),
    sa.ForeignKeyConstraint(['pocus_tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rounds')
    op.drop_table('defenders')
    op.drop_table('towers')
    # ### end Alembic commands ###
