"""

Revision ID: 32ae247f13ad
Revises: 
Create Date: 2021-11-16 18:25:40.931276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ae247f13ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towers', sa.Column('round_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('towers', 'round_id')
    # ### end Alembic commands ###
