"""

Revision ID: aae4bcfe7302
Revises: 13885ad9dbd6
Create Date: 2021-11-16 19:24:51.930795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae4bcfe7302'
down_revision = '13885ad9dbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towers', sa.Column('name', sa.VARCHAR(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('towers', 'name')
    # ### end Alembic commands ###
