# Config for logging
# ------------------
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema
version: 1
disable_existing_loggers: false
# Default (root) logger
root:
    level: !!python/name:logging.DEBUG
    handlers: [stdout]
loggers:
    # Logging from my application
    api:
        level: !!python/name:logging.DEBUG
        handlers: [logfile, stdout]
        propagate: false
    sqlalchemy.engine:
        level: !!python/name:logging.INFO
        handlers: [stdout]
        propagate: false
handlers:
    logfile:
        class: logging.FileHandler
        filename: storage/logs/template.log
        formatter: simpleFormatter
        level: !!python/name:logging.NOTSET
    stdout:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: simpleFormatter
        level: !!python/name:logging.NOTSET
    stderr:
        class: logging.StreamHandler
        stream: ext://sys.stderr
        formatter: simpleFormatter
        level: !!python/name:logging.NOTSET
formatters:
    simpleFormatter:
        class: logging.Formatter
        format: "[%(name)s]\t(%(asctime)s)\t- %(levelname)s - %(message)s"
        datefmt: '%d/%m/%Y %H:%M:%S'
